export const TITLE_COLOR = '#083133';
export const TRANSPARENT_COLOR = '#00000000';

export const RAIL_BORDER_COLOR = '#073436';
export const RAIL_BACKGROUND_COLOR = '#7CF3F9';
export const DISABLED_RAIL_BACKGROUND_COLOR = '#CBCBCB';

export const RAIL_FILL_BORDER_COLOR = '#3D797C';
export const RAIL_FILL_BACKGROUND_COLOR = '#D27030AA';

export const THUMB_ICON_BORDER_COLOR = '#3D797C';
export const THUMB_ICON_BACKGROUND_COLOR = '#D27030';

export const DISABLED_THUMB_ICON_BORDER_COLOR = '#3C3C3C';
export const DISABLED_THUMB_ICON_BACKGROUND_COLOR = '#D3D3D3';

export const SWIPE_SUCCESS_THRESHOLD = 70;
